

build:
  version: "1.0"

loans:
  message: "Welcome to EazyBank loans related prod API's"
  contactDetails:
    name: "Reine Aishwarya - Product Owner"
    email: "aishwarya@example.com"
  onCallSupport:
    -(453) 392-4829
    -(236) 203-0384