spring:
  application:
    name: "configserver"
  profiles:
    active: git
    #active: native
  cloud:
    config:
      server:
        #native:
          #search-locations: "classpath:/config"
          #search-locations: "file:///C://Users//Administrator//edison-vaz"
        git:
          uri: "https://github.com/Edisonpedruvaz009/eazybytes-config.git"
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true

encrypt:
  key: "45D81EC1EF61DF9AD8D3E5BB397F9"

server:
  port: 8071

