spring:
  config:
    activate:
        on-profile: "qa"

build:
  version: "2.0"

accounts:
  message: "Welcome to EazyBank accounts related QA API's"
  contactDetails:
    name: "Smitha Roy - QA Lead"
    email: "smitha@example.com"
  onCallSupport:
    -(666) 265-3765
    -(666) 734-8371